### ISSUE TITLE
server crash issues

### ISSUE THREAD

**Issue by Goatherde** [iamshift/PickablePiglins#1]
[Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.TreeMap$PrivateEntryIterator.nextEntry(TreeMap.java:1486) ~[?:?]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1522) ~[?:?]
	at java.util.TreeMap$EntryIterator.next(TreeMap.java:1517) ~[?:?]
	at com.shiftthedev.pickablepiglins.utils.CachedPiglins.save(CachedPiglins.java:212) ~[PickablePiglins-2.0.0+1.20.4-fabric.jar:?]
	at com.shiftthedev.pickablepiglins.PickablePiglins.lambda$init$1(PickablePiglins.java:32) ~[PickablePiglins-2.0.0+1.20.4-fabric.jar:?]
	at net.minecraft.class_3218.handler$zca000$architectury$save(class_3218.java:1777) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_14176(class_3218.java:811) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3723(MinecraftServer.java:542) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_39218(MinecraftServer.java:566) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:857) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[server-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by shiftthedev** [comment]
Unable to replicate.
Make sure you also have [Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-api), [Cloth Config](https://legacy.curseforge.com/minecraft/mc-mods/cloth-config) and [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api) in the mods folder.
